[12.0][ADD] epa_stock_request_custom: add new module custom
Escodoo/epa-addons pull request #27
Opened 2023-09-13 23:34 UTC by rodrigonevest

2023-09-14 22:06 UTC, rodrigonevest commented
c/c @marcelsavegnago

2023-09-18 18:21 UTC, marcelsavegnago requested changes

2023-09-18 18:21 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    valor = fields.Float(
nome do campo em ingles por favor

2023-09-18 18:21 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    valor = fields.Float(
nome do campo em ingles por favor

2023-09-18 20:41 UTC, kaynnan requested changes
Bom review funcional ok, porém falta incluir pelo o que recordo um campo solicitado pelo Augusto Lisboa e renomar a variavel para inglês.

2023-09-18 21:46 UTC, rodrigonevest commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    valor = fields.Float(
feito o ajuste.

2023-09-18 21:47 UTC, rodrigonevest commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    valor = fields.Float(
nome da variável de "valor" para "price_subtotal"

2023-09-18 21:47 UTC, rodrigonevest commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    valor = fields.Float(
feito o ajuste, de "valor" para "price_subtotal"

2023-09-18 22:51 UTC, marcelsavegnago commented
![image](https://github.com/Escodoo/epa-addons/assets/3595132/22d30288-09f6-42d5-93d9-e0ff92a2cef4)

Será que falta alguma dependencia ?

2023-09-19 16:16 UTC, marcelsavegnago requested changes

2023-09-19 16:16 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_project_stock_request_custom.py
> +class EpaProjectTaskStockRequestCustom(models.Model):
Nome da classe está errado.. deveria ser ProjectTask apenas

2023-09-19 16:16 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_project_stock_request_custom.py
> +    price_subtotal = fields.Float(
campo adicionado em modelo odoo deve começar com o prefixo epa_

2023-09-19 16:16 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +class EpaStockRequestOrderCustom(models.Model):
Nome da Classe deveria ser StockRequestOrder

2023-09-19 16:16 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    price_subtotal = fields.Float(
falta o prefixo epa_

2023-09-19 16:16 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    price_total = fields.Float(
falta o prefixo epa_

2023-09-19 16:16 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +class EpaStockRequestCustom(models.Model):
Classe deveria ser StockRequest

2023-09-19 16:16 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    price_subtotal = fields.Float(
campo em modelo do odoo devem ter o prefixo cliente_ .. no caso epa_

2023-09-19 16:16 UTC, marcelsavegnago commented on epa_stock_request_custom/models/epa_stock_request_custom.py
> +    def _compute_price_subtotal(self):
muda também o nome do método para _compute_epa_price_subtotal

2023-09-22 22:02 UTC, closed without merging

2023-09-22 22:02 UTC, rodrigonevest commented
Módulo criado em outra PR.