[12.0][ADD] egd_stock_request_custom: add new module
Escodoo/epa-addons pull request #28
Opened 2023-09-22 18:34 UTC by marcelsavegnago

2023-09-22 20:23 UTC, augustodinizl approved these changes
Excelente, ficou perfetio ao meu ver

![image](https://github.com/Escodoo/epa-addons/assets/25938418/91f3ab0d-dd94-41af-9ec8-61b7f6c4a741)
![image](https://github.com/Escodoo/epa-addons/assets/25938418/485694d3-c438-4111-8025-5d5b9235c850)

2023-09-22 22:01 UTC, rodrigonevest approved these changes
Revisão funcional ok.

2023-09-24 17:55 UTC, augustodinizl requested changes
Acabei de notar uma coisa, @rodrigonevest e @marcelsavegnago o total tá errado, pois ele não está multiplicando o valor unitário pelas quantidades para cada linha, isso gera erro

![image](https://github.com/Escodoo/epa-addons/assets/25938418/1287b208-8a26-459a-8a85-e1f4f8f64ead)

2023-09-25 13:14 UTC, marcelsavegnago commented
> Acabei de notar uma coisa, @rodrigonevest e @marcelsavegnago o total tá errado, pois ele não está multiplicando o valor unitário pelas quantidades para cada linha, isso gera erro
> 
> ![image](https://user-images.githubusercontent.com/25938418/270182598-1287b208-8a26-459a-8a85-e1f4f8f64ead.png)

A principio eu notei que em algumas situações se faz necessário salvar o registro. Não seria este o caso ?

2023-09-25 14:41 UTC, marcelsavegnago commented
@augustodinizl não consegui simular o problema que vc apresentou. Pode nos passar o roteiro para conseguir simular ?

2023-09-25 22:04 UTC, merged