[14.0] [MIG]  <epa_hr_attendances_overtime_custom>: Migration to 14.0.
Escodoo/epa-addons pull request #40
Opened 2023-12-28 17:51 UTC by Alisson-Jns

@marcelsavegnago @Escodoo/desenvolvedores

2024-01-31 02:12 UTC, kaynnan requested changes
A função `get_attendance` está com parametros/atributos invalidos para o funcionamento diante da versão 14.0, tem que realizar o debug / comparar os parametros que mudaram dessa função no módulo herdado da v12 para v14.

2024-01-31 02:12 UTC, kaynnan commented on epa_hr_attendances_overtime_custom/models/hr_attendance_sheet.py
> +    def get_attendance(self, data):
@Alisson-Jns essa função, possivelmente com alguns parametros desatualizados para a versão 14, quando eu clico para o Action acionar ele me retorna:

![image](https://github.com/Escodoo/epa-addons/assets/53870822/7f64a4d4-7a48-459d-b73b-936c0b17d950)

Realizei os testes primeiramente inicialmente separando a nossa custom e isso não ocorreu, o problema está localizado nessa função de nossa custom mesmo.

2024-02-07 00:33 UTC, kaynnan commented
@Alisson-Jns Como está o andamento das correções que foram solicitadas?

2024-02-08 20:03 UTC, Alisson-Jns commented on epa_hr_attendances_overtime_custom/models/hr_attendance_sheet.py
> +    def get_attendance(self, data):
@kaynnan   As alterações no codigo foram feitas, teste funcional ok
![Captura de tela de 2024-02-08 16-55-19](https://github.com/Escodoo/epa-addons/assets/77689372/db7005d2-f0e0-412d-9d62-38d505048783)

2024-02-08 21:29 UTC, kaynnan approved these changes
LGTM

2024-02-12 13:30 UTC, merged