[14.0][ADD] epa_hr_expense_advance_clearing_custom: add new module
Escodoo/epa-addons pull request #49
Opened 2024-04-16 20:46 UTC by WesleyOliveira98

2024-04-16 21:20 UTC, kaynnan commented on epa_hr_expense_advance_clearing_custom/readme/CONTRIBUTORS.rst
Ajustar os contribuidores, exemplo:

* `Escodoo <https://www.escodoo.com.br>`_:

  * Marcel Savegnago <marcel.savegnago@escodoo.com.br>
  * Wesley Oliveira <wesley.oliveira@escodoo.com.br>

2024-04-16 21:23 UTC, kaynnan requested changes
LGTM, mas precisa realizar os ajustes do README, questão de comentários no código deixar atualizado tipo 2024 - TODAY, etc.

Para atualizar o readme roda o seguinte comando:

`oca-gen-addon-readme --repo-name=$REPO --addon-dir=$MODULE --branch=$VERSION --org-name=$USER_ORG`

2024-04-16 21:23 UTC, kaynnan commented on epa_hr_expense_advance_clearing_custom/views/hr_expense_sheet.xml
> +<!-- Copyright 2022 - TODAY, Escodoo
2024 - TODAY, Wesley Oliveira <wesley.oliveira@escodoo.com.br>

2024-04-16 21:23 UTC, kaynnan commented on epa_hr_expense_advance_clearing_custom/__manifest__.py
> +# Copyright 2022 - TODAY, Escodoo
2024 - TODAY, Escodoo

2024-04-17 13:31 UTC, kaynnan approved these changes

2024-04-17 14:13 UTC, marcelsavegnago approved these changes

2024-04-17 14:13 UTC, merged