[ADD] epa_account_manager: add new module
Escodoo/epa-addons pull request #53
Opened 2024-04-26 21:46 UTC by Matthwhy

2024-04-28 23:41 UTC, kaynnan approved these changes
LGTM

2024-04-29 11:58 UTC, WesleyOliveira98 approved these changes
LGTM

2024-04-29 12:00 UTC, WesleyOliveira98 requested changes
@Matthwhy só incluir a versão no nome da PR, exemplo: [14.0][ADD]

2024-04-29 15:14 UTC, marcelsavegnago commented on epa_account_manager/models/account_move.py
> +                record.manager_id = analytic_accounts[0].manager_id.id
Vale um or False para evitar problema ?

2024-05-02 19:12 UTC, marcelsavegnago commented on epa_account_manager/readme/CONTRIBUTORS.rst
> +* `ESCODOO <https://escodoo.com.br>`_:
Escodoo

2024-05-02 20:07 UTC, marcelsavegnago approved these changes

2024-05-02 20:07 UTC, merged