[14.0][IMP] epa_hr_expense_custom: backport static fields to module
Escodoo/epa-addons pull request #67
Opened 2024-08-01 10:21 UTC by kaynnan

HT00743

Objetivo: possibilitar edição do campo quando o `state` for igual a `draft`.

Como esse campo foi definido pela interface do Odoo, o que não é uma boa prática, a ideia principal foi realizar o backport considerando as mesmas regras do campo, nome, definidas pela interface para o modelo `hr.expense`.

Temos outro campo que seria necessário trazer para o backport, não sei se vem ao caso, mas estarei colocando a print de como ele foi definido.

![image](https://github.com/user-attachments/assets/81822f79-2582-47be-b616-4013629eaaf0)

cc @WesleyOliveira98 @marcelsavegnago @douglascstd

2024-08-01 11:24 UTC, WesleyOliveira98 requested changes

2024-08-01 11:24 UTC, WesleyOliveira98 commented on epa_hr_expense_custom/models/hr_expense.py
> +    )
Não usar `x_nf` e `x_nf_partner` que seguem o padrão de campos criados via interface, sugiro usar `fiscal_document_number` e `fiscal_document_partner_id`. Os campos não precisam ter o mesmo nome do campo da interface, a gente vai popular esses novos campos via export/import

2024-08-01 11:37 UTC, douglascstd commented on epa_hr_expense_custom/models/hr_expense.py
> +    )
vejo que o caminho que o Wesley comentou parece ser mais seguro..

2024-08-01 11:38 UTC, WesleyOliveira98 requested changes

2024-08-01 11:38 UTC, WesleyOliveira98 commented on epa_hr_expense_custom/views/hr_expense.xml
Adicionar os campos na tree view para permitir a edição, ou então, adicionar o atributo `editable` no campo `expense_line_ids` para abrir o formulário ao tentar editar uma linha (exemplo https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_purchase/views/purchase_view.xml#L40)

2024-08-01 12:29 UTC, kaynnan commented
Valeu pessoal pela revisão, realizei os ajustes

2024-08-01 12:52 UTC, WesleyOliveira98 approved these changes
LGTM

2024-08-06 13:00 UTC, kaynnan commented
ping @marcelsavegnago

2024-08-06 13:33 UTC, marcelsavegnago commented
Já foi testado ou deve ser incluido no ambiente staging ?

2024-08-06 13:35 UTC, kaynnan commented
> Já foi testado ou deve ser incluido no ambiente staging ?

Testado local, precisava ser colocado na Staging para testar a questão de importar/exportar os valores dos campos antigos para os novos

2024-08-06 17:45 UTC, marcelsavegnago commented
inclui agora na staging

2024-08-07 17:22 UTC, kaynnan commented
@marcelsavegnago 

Testes realizados na Staging e funcionamento correto, podemos seguir com o merge ?

2024-08-12 12:48 UTC, marcelsavegnago approved these changes

2024-08-12 12:48 UTC, merged