[14.0][WIP] epa_sale_crm_custom: add new module
Escodoo/epa-addons pull request #73
Opened 2024-09-09 16:26 UTC by kaynnan

cc @marcelsavegnago @WesleyOliveira98 

![image](https://github.com/user-attachments/assets/48c0bb78-88cf-4b39-952e-c61ca8a491d7)

- [ ] Sequence in sale.order
- [ ] Project assumes the same name as the sale.order, removing the SO prefix

2024-09-27 21:03 UTC, WesleyOliveira98 approved these changes
LGTM

2024-10-07 20:19 UTC, marcelsavegnago commented
podemos mesclar ?

2024-10-07 20:21 UTC, kaynnan commented
> podemos mesclar ?

Por momento acredito que sim, estamos aguardando o cliente retornar das ferias para apresentar, mas qualquer mudança abro uma nova PR, por momento, mantem somente na Staging

2024-10-14 19:01 UTC, WesleyOliveira98 requested changes

2024-10-14 19:01 UTC, WesleyOliveira98 commented on epa_sale_crm_custom/data/sequence.xml
> +        <field name="prefix">%(y)s-</field>
Aqui pode manter o `SO-%(y)s`

2024-10-24 13:01 UTC, WesleyOliveira98 approved these changes
LGTM

2024-12-02 18:58 UTC, WesleyOliveira98 approved these changes
LGTM

2024-12-02 21:25 UTC, merged